name: Telegraf source
language: docker
variables:
  - name: output
    inputType: OutputTopic
    description: This is the Quix Topic that will receive the stream
    defaultValue: telegraf
    required: true
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: telegraf-source
